logo: logo_tsk_creative.svg
title: TSKCreative
description: > # this means to ignore newlines until "baseurl:"
  TSK Creative specializes in graphic and web design.  Tiffany Stedman Kotowski is based out of Chicago, IL.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sted0011.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: MovingStripes.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: Tiffany_Stedman.jpg # your photo
author-name: Tiffany Stedman Kotowski # your name
about-author: # about author
email: tiffany@tskcreative.com # your email
phone:  # your pnone number
website: https://sted0011.github.io/ # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link
instagram_url: https://www.instagram.com/tskcreative/ # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link

# Disqus
discus_identifier:  # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Build settings
markdown: kramdown

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
